### ISSUE TITLE
upgrades

### ISSUE THREAD

**Issue by YashasSingh** [baldingwizard/python-pygame-asteroids#1]
Hey i was wondering if i can add try and add an upgrade feature, any ideas how

or maybe bots enemies that attack you

**Comment by baldingwizard** [comment]
Of course - just use the GitHub 'Fork' option at the top to create your own copy of the repository and then you can make any changes you desire.
I was previously looking into adding 'powerups' where some asteroids would leave behind power that could be picked up. These would then be used to enhance your ship - eg, faster shooting, longer-range bullets, that kind of thing.
Adding enemies that attack is a great idea. It should be achievable by following a similar approach to how the asteroids are handled - ie, have a list of enemies and then process each in turn, updating the location, etc. and have a loop to paint them on each frame.
It's a long time since I worked on this so it isn't fresh in my mind. Give it a try - I'd be really interested to see where you take it :-)
